# Generated by Django 3.2 on 2022-04-26 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='engravingtechnique',
            old_name='low_order_price',
            new_name='cm2_price',
        ),
        migrations.AddField(
            model_name='engravingtechnique',
            name='cliche_price',
            field=models.FloatField(default=20.0),
        ),
        migrations.AddField(
            model_name='engravingtechnique',
            name='order_under_request',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='engravingtechnique',
            name='terms',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='engravingtechnique',
            name='color1_1',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='engravingtechnique',
            name='color1_10',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='engravingtechnique',
            name='color1_100',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='engravingtechnique',
            name='color1_1000',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='engravingtechnique',
            name='color1_2000',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='engravingtechnique',
            name='color1_250',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='engravingtechnique',
            name='color1_50',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='engravingtechnique',
            name='color1_500',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='engravingtechnique',
            name='color1_5000',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='engravingtechnique',
            name='color2_1',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='engravingtechnique',
            name='color2_10',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='engravingtechnique',
            name='color2_100',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='engravingtechnique',
            name='color2_1000',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='engravingtechnique',
            name='color2_2000',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='engravingtechnique',
            name='color2_250',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='engravingtechnique',
            name='color2_50',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='engravingtechnique',
            name='color2_500',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='engravingtechnique',
            name='color2_5000',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=6, null=True),
        ),
    ]
