# Generated by Django 3.2 on 2022-04-26 19:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0002_auto_20220426_1538'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='engravingtechnique',
            name='cm2',
        ),
    ]
