# Generated by Django 3.2 on 2022-04-27 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0003_remove_engravingtechnique_cm2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='engravingtechnique',
            name='cm2_price',
        ),
        migrations.RemoveField(
            model_name='engravingtechnique',
            name='code_pfconcept',
        ),
        migrations.RemoveField(
            model_name='engravingtechnique',
            name='color1_1',
        ),
        migrations.RemoveField(
            model_name='engravingtechnique',
            name='color1_10',
        ),
        migrations.RemoveField(
            model_name='engravingtechnique',
            name='color1_100',
        ),
        migrations.RemoveField(
            model_name='engravingtechnique',
            name='color1_1000',
        ),
        migrations.RemoveField(
            model_name='engravingtechnique',
            name='color1_2000',
        ),
        migrations.RemoveField(
            model_name='engravingtechnique',
            name='color1_250',
        ),
        migrations.RemoveField(
            model_name='engravingtechnique',
            name='color1_50',
        ),
        migrations.RemoveField(
            model_name='engravingtechnique',
            name='color1_500',
        ),
        migrations.RemoveField(
            model_name='engravingtechnique',
            name='color1_5000',
        ),
        migrations.RemoveField(
            model_name='engravingtechnique',
            name='color2_1',
        ),
        migrations.RemoveField(
            model_name='engravingtechnique',
            name='color2_10',
        ),
        migrations.RemoveField(
            model_name='engravingtechnique',
            name='color2_100',
        ),
        migrations.RemoveField(
            model_name='engravingtechnique',
            name='color2_1000',
        ),
        migrations.RemoveField(
            model_name='engravingtechnique',
            name='color2_2000',
        ),
        migrations.RemoveField(
            model_name='engravingtechnique',
            name='color2_250',
        ),
        migrations.RemoveField(
            model_name='engravingtechnique',
            name='color2_50',
        ),
        migrations.RemoveField(
            model_name='engravingtechnique',
            name='color2_500',
        ),
        migrations.RemoveField(
            model_name='engravingtechnique',
            name='color2_5000',
        ),
        migrations.RemoveField(
            model_name='engravingtechnique',
            name='included_color',
        ),
        migrations.RemoveField(
            model_name='engravingtechnique',
            name='minimum_price_per_unit',
        ),
        migrations.AddField(
            model_name='engravingtechnique',
            name='cm_price_1',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='engravingtechnique',
            name='cm_price_2',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='engravingtechnique',
            name='cm_price_3',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='engravingtechnique',
            name='cm_price_4',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='engravingtechnique',
            name='cm_price_5',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='engravingtechnique',
            name='cm_price_6',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='engravingtechnique',
            name='cm_price_7',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='engravingtechnique',
            name='color1_aditional',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='engravingtechnique',
            name='color1_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='engravingtechnique',
            name='color2_aditional',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='engravingtechnique',
            name='color2_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='engravingtechnique',
            name='color3_aditional',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='engravingtechnique',
            name='color3_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='engravingtechnique',
            name='color4_aditional',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='engravingtechnique',
            name='color4_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='engravingtechnique',
            name='color5_aditional',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='engravingtechnique',
            name='color5_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='engravingtechnique',
            name='color6_aditional',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='engravingtechnique',
            name='color6_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='engravingtechnique',
            name='color7_aditional',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='engravingtechnique',
            name='color7_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='engravingtechnique',
            name='is_cliche_repeated',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='engravingtechnique',
            name='min_amount_1',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='engravingtechnique',
            name='min_amount_2',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='engravingtechnique',
            name='min_amount_3',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='engravingtechnique',
            name='min_amount_4',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='engravingtechnique',
            name='min_amount_5',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='engravingtechnique',
            name='min_amount_6',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='engravingtechnique',
            name='min_amount_7',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='engravingtechnique',
            name='repeated_cliche_price',
            field=models.FloatField(default=15.0),
        ),
        migrations.AlterField(
            model_name='engravingtechnique',
            name='cliche_price',
            field=models.FloatField(default=30.0),
        ),
        migrations.AlterField(
            model_name='engravingtechnique',
            name='minimum_work',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5, null=True),
        ),
    ]
