# Generated by Django 3.2 on 2022-04-27 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0004_auto_20220427_1618'),
    ]

    operations = [
        migrations.AddField(
            model_name='engravingtechnique',
            name='min_amount',
            field=models.IntegerField(default=0),
        ),
    ]
