# Generated by Django 3.2 on 2022-04-27 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0005_engravingtechnique_min_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='engravingtechnique',
            name='block_import',
            field=models.BooleanField(default=False),
        ),
    ]
