# Generated by Django 3.2 on 2022-05-10 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0007_alter_engravingtechnique_min_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='engravingarea',
            name='code_pfconcept',
        ),
        migrations.RemoveField(
            model_name='engravingarea',
            name='engraving_technique',
        ),
        migrations.AddField(
            model_name='engravingarea',
            name='engraving_technique',
            field=models.ManyToManyField(to='ecommerce.EngravingTechnique'),
        ),
    ]
