# Generated by Django 3.2 on 2021-12-27 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(default='', max_length=250)),
                ('slug', models.SlugField(allow_unicode=True, editable=False, max_length=250)),
                ('is_active', models.BooleanField(default=True)),
                ('show_in_menu_list', models.BooleanField(default=True)),
                ('is_favorite', models.BooleanField(default=True)),
                ('makito_id', models.CharField(blank=True, default=None, max_length=50, null=True)),
                ('pfconcept_id', models.CharField(blank=True, default=None, max_length=50, null=True)),
                ('sticker_id', models.CharField(blank=True, default=None, max_length=50, null=True)),
                ('pfconcept_name', models.CharField(blank=True, default=None, max_length=250, null=True)),
                ('figure_name', models.CharField(blank=True, default=None, max_length=250, null=True)),
                ('rolly_name', models.CharField(blank=True, default=None, max_length=250, null=True)),
                ('jhk_name', models.CharField(blank=True, default=None, max_length=250, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'ecommerce_category',
                'ordering': ['category_name'],
            },
        ),
    ]
