# Generated by Django 3.2 on 2021-12-27 04:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0003_remove_category_deleted_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color_name', models.CharField(default='', max_length=250)),
                ('slug', models.SlugField(allow_unicode=True, editable=False, max_length=250)),
                ('description', models.TextField(default=None)),
                ('basic_color', models.CharField(blank=True, default=None, max_length=80, null=True)),
                ('simple_color', models.CharField(blank=True, default=None, max_length=80, null=True)),
                ('primary_color', models.CharField(blank=True, default=None, max_length=80, null=True)),
                ('secondary_color', models.CharField(blank=True, default=None, max_length=80, null=True)),
                ('sticker_id', models.CharField(blank=True, default=None, max_length=50, null=True)),
                ('sticker_name', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('pfconcept_color', models.CharField(blank=True, default=None, max_length=50, null=True)),
                ('pms_color_reference', models.CharField(blank=True, default=None, max_length=50, null=True)),
                ('jhk_color', models.CharField(blank=True, default=None, max_length=50, null=True)),
                ('jhk_color_reference', models.CharField(blank=True, default=None, max_length=50, null=True)),
                ('roly_color', models.CharField(blank=True, default=None, max_length=50, null=True)),
                ('roly_color_id', models.CharField(blank=True, default=None, max_length=50, null=True)),
                ('makito_color', models.CharField(blank=True, default=None, max_length=50, null=True)),
                ('makito_color_ftp', models.CharField(blank=True, default=None, max_length=50, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('parent_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subcategory', to='ecommerce.color')),
            ],
            options={
                'db_table': 'ecommerce_color',
                'ordering': ['color_name'],
            },
        ),
    ]
