# Generated by Django 3.2 on 2021-12-27 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0004_color'),
    ]

    operations = [
        migrations.CreateModel(
            name='Size',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size_name', models.CharField(default='', max_length=250)),
                ('slug', models.SlugField(allow_unicode=True, editable=False, max_length=250)),
                ('cifra_size', models.CharField(blank=True, default=None, max_length=50, null=True)),
                ('makito_size', models.CharField(blank=True, default=None, max_length=50, null=True)),
                ('pfconcept_size', models.CharField(blank=True, default=None, max_length=50, null=True)),
                ('roly_size', models.CharField(blank=True, default=None, max_length=50, null=True)),
                ('roly_size_id', models.CharField(blank=True, default=None, max_length=50, null=True)),
                ('order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'ecommerce_size',
                'ordering': ['size_name'],
            },
        ),
    ]
