# Generated by Django 3.2 on 2021-12-27 06:15

from django.db import migrations, models
import django.db.models.deletion
import ecommerce.models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0005_size'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(default='', max_length=250)),
                ('slug', models.SlugField(allow_unicode=True, editable=False, max_length=250)),
                ('product_description', models.TextField(default=None)),
                ('product_description_additional', models.TextField(default=None)),
                ('product_image', models.ImageField(blank=True, null=True, upload_to=ecommerce.models.get_product_image_upload_path)),
                ('product_image_url', models.CharField(blank=True, default=None, max_length=250, null=True)),
                ('product_thumbnail_image', models.ImageField(blank=True, null=True, upload_to=ecommerce.models.get_product_thumbnail_upload_path)),
                ('provider', models.CharField(blank=True, default='publiexpe', max_length=250, null=True)),
                ('repeated_position', models.IntegerField(default=0)),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, null=True)),
                ('net_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, null=True)),
                ('stock', models.IntegerField(default=0)),
                ('accept_order_when_out_of_stock', models.BooleanField(default=False)),
                ('max_reserve_quantity', models.IntegerField(default=50)),
                ('available_from', models.DateTimeField(auto_now=True)),
                ('reference', models.CharField(blank=True, default=None, max_length=250, null=True)),
                ('root_reference', models.CharField(blank=True, default=None, max_length=250, null=True)),
                ('show_color_to_order', models.BooleanField(default=False)),
                ('weight', models.DecimalField(decimal_places=2, default=0.0, max_digits=6)),
                ('depth', models.DecimalField(decimal_places=2, default=0.0, max_digits=6)),
                ('width', models.DecimalField(decimal_places=2, default=0.0, max_digits=6)),
                ('height', models.DecimalField(decimal_places=2, default=0.0, max_digits=6)),
                ('combined_measured', models.CharField(blank=True, default=None, max_length=250, null=True)),
                ('box_units', models.DecimalField(decimal_places=2, default=0.0, max_digits=6)),
                ('sell_per_box', models.BooleanField(default=False)),
                ('minimum_order', models.IntegerField(default=1)),
                ('pallet_box', models.DecimalField(decimal_places=2, default=0.0, max_digits=6)),
                ('box_gross_weight', models.DecimalField(decimal_places=2, default=0.0, max_digits=6)),
                ('box_net_weight', models.DecimalField(decimal_places=2, default=0.0, max_digits=6)),
                ('box_dimension', models.DecimalField(decimal_places=2, default=0.0, max_digits=6)),
                ('material', models.CharField(blank=True, default=None, max_length=250, null=True)),
                ('total_visit', models.IntegerField(default=0)),
                ('is_published', models.BooleanField(default=True)),
                ('is_featured', models.BooleanField(default=True)),
                ('link_360', models.CharField(blank=True, default=None, max_length=250, null=True)),
                ('link_video1', models.CharField(blank=True, default=None, max_length=250, null=True)),
                ('link_video2', models.CharField(blank=True, default=None, max_length=250, null=True)),
                ('outlet', models.BooleanField(default=False)),
                ('is_new', models.BooleanField(default=True)),
                ('is_most_sold', models.BooleanField(default=False)),
                ('liquidation', models.BooleanField(default=True)),
                ('settlement_position', models.CharField(choices=[('LEFT_UP', 'LEFT_UP'), ('LEFT_DOWN', 'LEFT_DOWN'), ('RIGHT_UP', 'RIGHT_UP'), ('RIGHT_DOWN', 'RIGHT_DOWN')], default='LEFT_UP', max_length=10)),
                ('liquidation_text', models.CharField(blank=True, default=None, max_length=250, null=True)),
                ('liquidation_background_color', models.CharField(blank=True, default='#000000', max_length=8, null=True)),
                ('liquidation_text_color', models.CharField(blank=True, default='#FFFFFF', max_length=8, null=True)),
                ('is_seal_activated', models.BooleanField(default=False)),
                ('is_discount_allowed', models.BooleanField(default=False)),
                ('protect_import', models.BooleanField(default=False)),
                ('protect_image', models.BooleanField(default=False)),
                ('datasheet', models.FileField(blank=True, null=True, upload_to=ecommerce.models.get_product_datasheet_upload_path)),
                ('imported_json_data', models.JSONField(blank=True, default=None, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='belongs_to_category', to='ecommerce.category')),
                ('color', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='belongs_to_color', to='ecommerce.color')),
                ('size', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='belongs_to_size', to='ecommerce.size')),
            ],
        ),
    ]
