# Generated by Django 3.2 on 2021-12-29 03:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0006_product'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['product_name']},
        ),
        migrations.AlterModelTable(
            name='product',
            table='ecommerce_product',
        ),
    ]
