# Generated by Django 3.2 on 2021-12-29 04:08

from django.db import migrations, models
import django.db.models.deletion
import ecommerce.models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0008_productimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductAnnouncement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=250)),
                ('slug', models.SlugField(allow_unicode=True, editable=False, max_length=250)),
                ('adjective', models.CharField(blank=True, max_length=250, null=True)),
                ('title', models.CharField(default='', max_length=250)),
                ('subtitle', models.CharField(default='', max_length=250)),
                ('image', models.ImageField(blank=True, null=True, upload_to=ecommerce.models.get_product_image_upload_path)),
                ('text_bottom', models.CharField(blank=True, max_length=250, null=True)),
                ('right_position', models.BooleanField(default=True)),
                ('text_color', models.CharField(blank=True, default='#000000', max_length=8, null=True)),
                ('url', models.CharField(default='', max_length=250)),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.IntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_product_announcement', to='ecommerce.product')),
            ],
            options={
                'db_table': 'ecommerce_product_announcement',
                'ordering': ['-created_at'],
            },
        ),
    ]
