# Generated by Django 3.2 on 2021-12-29 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0009_productannouncement'),
    ]

    operations = [
        migrations.CreateModel(
            name='EngravingTechnique',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('engraving_technique_name', models.CharField(default='', max_length=250)),
                ('slug', models.SlugField(allow_unicode=True, editable=False, max_length=250)),
                ('code_makito', models.CharField(blank=True, max_length=150, null=True)),
                ('code_pfconcept', models.CharField(blank=True, max_length=150, null=True)),
                ('max_color', models.IntegerField(default=1)),
                ('included_color', models.IntegerField(default=1)),
                ('minimum_work', models.DecimalField(decimal_places=2, default=20.0, max_digits=10, null=True)),
                ('minimum_price_per_unit', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, null=True)),
                ('low_order_price', models.BooleanField(default=False)),
                ('cm2', models.BooleanField(default=False)),
                ('select_color', models.BooleanField(default=True)),
                ('protect_import', models.BooleanField(default=False)),
                ('color1_1', models.DecimalField(decimal_places=2, default=1.0, max_digits=6, null=True)),
                ('color1_10', models.DecimalField(decimal_places=2, default=1.0, max_digits=6, null=True)),
                ('color1_50', models.DecimalField(decimal_places=2, default=1.0, max_digits=6, null=True)),
                ('color1_100', models.DecimalField(decimal_places=2, default=1.0, max_digits=6, null=True)),
                ('color1_250', models.DecimalField(decimal_places=2, default=1.0, max_digits=6, null=True)),
                ('color1_500', models.DecimalField(decimal_places=2, default=1.0, max_digits=6, null=True)),
                ('color1_1000', models.DecimalField(decimal_places=2, default=1.0, max_digits=6, null=True)),
                ('color1_2000', models.DecimalField(decimal_places=2, default=1.0, max_digits=6, null=True)),
                ('color1_5000', models.DecimalField(decimal_places=2, default=1.0, max_digits=6, null=True)),
                ('color2_1', models.DecimalField(decimal_places=2, default=1.0, max_digits=6, null=True)),
                ('color2_10', models.DecimalField(decimal_places=2, default=1.0, max_digits=6, null=True)),
                ('color2_50', models.DecimalField(decimal_places=2, default=1.0, max_digits=6, null=True)),
                ('color2_100', models.DecimalField(decimal_places=2, default=1.0, max_digits=6, null=True)),
                ('color2_250', models.DecimalField(decimal_places=2, default=1.0, max_digits=6, null=True)),
                ('color2_500', models.DecimalField(decimal_places=2, default=1.0, max_digits=6, null=True)),
                ('color2_1000', models.DecimalField(decimal_places=2, default=1.0, max_digits=6, null=True)),
                ('color2_2000', models.DecimalField(decimal_places=2, default=1.0, max_digits=6, null=True)),
                ('color2_5000', models.DecimalField(decimal_places=2, default=1.0, max_digits=6, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'ecommerce_engraving_technique',
                'ordering': ['engraving_technique_name'],
            },
        ),
    ]
