# Generated by Django 3.2 on 2021-12-29 04:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0010_engravingtechnique'),
    ]

    operations = [
        migrations.CreateModel(
            name='EngravingTechniqueColor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=250)),
                ('slug', models.SlugField(allow_unicode=True, editable=False, max_length=250)),
                ('n_colors', models.IntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('engraving_technique', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='belongs_to_engraving_technique', to='ecommerce.product')),
            ],
            options={
                'db_table': 'ecommerce_engraving_technique_color',
                'ordering': ['name'],
            },
        ),
    ]
