# Generated by Django 3.2 on 2021-12-29 04:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0011_engravingtechniquecolor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='engravingtechniquecolor',
            name='engraving_technique',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='belongs_to_engraving_technique', to='ecommerce.engravingtechnique'),
        ),
    ]
