# Generated by Django 3.2 on 2021-12-29 05:08

from django.db import migrations, models
import django.db.models.deletion
import ecommerce.models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0012_alter_engravingtechniquecolor_engraving_technique'),
    ]

    operations = [
        migrations.CreateModel(
            name='EngravedArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=250)),
                ('display_name', models.CharField(default='', max_length=250)),
                ('slug', models.SlugField(allow_unicode=True, editable=False, max_length=250)),
                ('code_makito', models.CharField(blank=True, max_length=150, null=True)),
                ('code_pfconcept', models.CharField(blank=True, max_length=150, null=True)),
                ('width', models.DecimalField(decimal_places=2, default=0.0, max_digits=6)),
                ('height', models.DecimalField(decimal_places=2, default=0.0, max_digits=6)),
                ('diameter', models.DecimalField(decimal_places=2, default=0.0, max_digits=6)),
                ('image', models.ImageField(blank=True, null=True, upload_to=ecommerce.models.get_engraved_area_image_upload_path)),
                ('is_modified', models.BooleanField(default=False)),
                ('is_deprecated', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('engraving_technique', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='engraving_technique_engraved_area', to='ecommerce.engravingtechnique')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_engraved_area', to='ecommerce.product')),
            ],
            options={
                'db_table': 'ecommerce_engraved_area',
                'ordering': ['name'],
            },
        ),
    ]
