# Generated by Django 3.2 on 2022-01-09 20:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0015_size_jhk_size'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='size',
            options={'ordering': ['order']},
        ),
        migrations.RenameField(
            model_name='category',
            old_name='figure_name',
            new_name='cifra_name',
        ),
    ]
