# Generated by Django 3.2 on 2022-01-12 18:54

from django.db import migrations, models
import ecommerce.models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0016_auto_20220109_2017'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_description_additional',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_image',
            field=models.ImageField(default=None, upload_to=ecommerce.models.get_product_image_upload_path),
        ),
    ]
