# Generated by Django 3.2 on 2022-01-12 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0018_alter_product_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='total_visit',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
