# Generated by Django 3.2 on 2022-02-28 13:49

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0020_alter_category_parent_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='tags',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=25, null=True), default=[], size=50),
        ),
    ]
