# Generated by Django 3.2 on 2022-03-01 09:12

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import ecommerce.models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0023_auto_20220228_1650'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productimage',
            name='product_image',
            field=models.FileField(blank=True, null=True, upload_to=ecommerce.models.get_product_image_upload_path, validators=[django.core.validators.FileExtensionValidator(['png', 'jpg', 'jpeg'])]),
        ),
        migrations.CreateModel(
            name='ProductTopSeller',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sales', models.IntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_top_seller', to='ecommerce.product')),
            ],
            options={
                'db_table': 'product_top_seller',
                'ordering': ['-updated_at', 'sales'],
            },
        ),
    ]
