# Generated by Django 3.2 on 2022-03-02 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0026_auto_20220302_0016'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='sub_category',
            field=models.ManyToManyField(blank=True, null=True, related_name='subcategories', to='ecommerce.Category'),
        ),
    ]
