# Generated by Django 3.2 on 2022-03-02 20:51

from django.db import migrations, models
import ecommerce.models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0028_alter_product_sub_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='color',
            name='makito_color_ftp',
        ),
        migrations.AddField(
            model_name='product',
            name='product_thumbnail_image',
            field=models.ImageField(blank=True, null=True, upload_to=ecommerce.models.get_product_thumbnail_upload_path),
        ),
    ]
