# Generated by Django 3.2 on 2022-05-16 18:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0006_auto_20220516_0048'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderitem',
            old_name='product',
            new_name='variant_id',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='ordered',
        ),
    ]
