# Generated by Django 3.2 on 2022-05-16 18:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0007_auto_20220516_1854'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderitem',
            old_name='variant_id',
            new_name='variant',
        ),
    ]
