# Generated by Django 3.2 on 2022-05-16 19:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0009_auto_20220516_1927'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderitem',
            old_name='order',
            new_name='cart',
        ),
    ]
