# Generated by Django 3.2 on 2022-02-06 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_alter_shippingaddress_auth_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='cookies_accepted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='cookies_version',
            field=models.CharField(blank=True, default=None, max_length=4, null=True),
        ),
    ]
