# Generated by Django 3.2 on 2022-02-07 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_userprofile_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='billingaddress',
            name='country',
            field=models.CharField(default='ES', max_length=2),
        ),
        migrations.AddField(
            model_name='billingaddress',
            name='email',
            field=models.CharField(max_length=60, null=True),
        ),
    ]
