# Generated by Django 3.2 on 2022-02-09 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_alter_shippingaddress_auth_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='phone_number',
            field=models.BigIntegerField(default=0),
        ),
    ]
