# Generated by Django 3.2 on 2022-02-17 12:27

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=250)),
                ('cif', models.CharField(max_length=13, unique=True)),
                ('address', models.CharField(max_length=100)),
                ('address_extra', models.CharField(blank=True, max_length=100, null=True)),
                ('locality', models.CharField(max_length=35)),
                ('city', models.CharField(max_length=50)),
                ('postal_code', models.IntegerField()),
                ('phone_number', models.BigIntegerField(default=0)),
                ('slug', models.SlugField(allow_unicode=True, editable=False, max_length=250, null=True)),
                ('tariff_global', models.FloatField(default=0, max_length=5)),
                ('tariff_engraving', models.FloatField(default=0, max_length=5)),
                ('vat', models.FloatField(blank=True, null=True)),
                ('vat_show_in_products', models.BooleanField(default=False)),
                ('vat_prefix', models.CharField(max_length=10, null=True)),
                ('shipping_measure_unit', models.CharField(max_length=5, null=True)),
                ('shipping_dimension_unit', models.CharField(max_length=5, null=True)),
                ('shipping_calculate_in_cart', models.BooleanField(default=False)),
                ('shipping_to', models.CharField(choices=[('SHIPPING_ADDRESS', 'SHIPPING_ADDRESS'), ('BILLING_ADDRESS', 'BILLING_ADDRESS')], default='SHIPPING_ADDRESS', max_length=20)),
                ('product_active_review', models.BooleanField(default=False)),
                ('product_active_rating', models.BooleanField(default=False)),
                ('stock_active_management', models.BooleanField(default=False)),
                ('stock_low_threshold', models.IntegerField(default=0, null=True)),
                ('stock_high_threshold', models.IntegerField(default=0, null=True)),
                ('stock_out_hidde_product', models.BooleanField(default=False)),
                ('cart_active', models.BooleanField(default=True)),
                ('cuppons_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'company_settings',
            },
        ),
        migrations.CreateModel(
            name='DataProtection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_text', models.CharField(blank=True, max_length=200, null=True)),
                ('legal_advise', models.TextField(blank=True, max_length=1500, null=True)),
                ('cookies_international', models.TextField(blank=True, max_length=3500, null=True)),
                ('cookies_web', models.TextField(blank=True, max_length=200, null=True)),
                ('terms_and_conditions', models.TextField(blank=True, max_length=5000, null=True)),
                ('version', models.FloatField(default='0.0')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'data_protection',
            },
        ),
        migrations.CreateModel(
            name='Shipping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(allow_unicode=True, editable=False, max_length=250, null=True)),
                ('zone_name', models.CharField(max_length=20)),
                ('regions', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=10), size=100)),
            ],
            options={
                'db_table': 'shippings',
            },
        ),
        migrations.CreateModel(
            name='ShippingMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(allow_unicode=True, editable=False, max_length=250, null=True)),
                ('shipping_name', models.CharField(max_length=30)),
                ('is_active', models.BooleanField(default=False)),
                ('description', models.CharField(max_length=100, null=True)),
                ('price', models.IntegerField()),
                ('shipping_zone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shippings_methods', to='dashboard.shipping')),
            ],
            options={
                'db_table': 'shipping_method',
            },
        ),
    ]
