# Generated by Django 3.2 on 2022-02-17 12:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shippingmethod',
            name='shipping_zone',
        ),
        migrations.AddField(
            model_name='shipping',
            name='shippings_methods',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='shippings_methods', to='dashboard.shippingmethod'),
            preserve_default=False,
        ),
    ]
