# Generated by Django 3.2 on 2022-02-17 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_auto_20220217_1341'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shipping',
            name='shippings_methods',
        ),
        migrations.AddField(
            model_name='shipping',
            name='shippings_methods',
            field=models.ManyToManyField(related_name='shippings_methods', to='dashboard.ShippingMethod'),
        ),
    ]
