# Generated by Django 3.2 on 2022-02-17 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_auto_20220217_1347'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipping',
            name='type',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
