# Generated by Django 3.2 on 2022-02-17 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_shipping_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shipping',
            name='type',
        ),
        migrations.RemoveField(
            model_name='shippingmethod',
            name='shipping_name',
        ),
        migrations.AddField(
            model_name='shippingmethod',
            name='type',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
