# Generated by Django 3.2 on 2022-02-17 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_auto_20220217_1542'),
    ]

    operations = [
        migrations.AddField(
            model_name='shippingmethod',
            name='name',
            field=models.CharField(default='', max_length=30),
            preserve_default=False,
        ),
    ]
