# Generated by Django 3.2 on 2022-02-17 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_shippingmethod_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shippingmethod',
            name='type',
            field=models.CharField(choices=[('FREE', 'FREE'), ('FLAT', 'FLAT'), ('CUSTOM', 'CUSTOM')], max_length=20, null=True),
        ),
    ]
