# Generated by Django 3.2 on 2022-02-17 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_alter_shippingmethod_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='shippingmethod',
            name='requirement',
            field=models.CharField(choices=[('MIN_AMOUNT', 'MIN_AMOUNT'), ('COUPON', 'COUPON'), ('EITHER', 'EITHER')], max_length=20, null=True),
        ),
    ]
