# Generated by Django 3.2 on 2022-02-17 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0008_shippingmethod_requirement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shippingmethod',
            name='price',
            field=models.FloatField(),
        ),
    ]
