# Generated by Django 3.2 on 2022-02-17 18:55

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0009_alter_shippingmethod_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipping',
            name='regions',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=50), size=100),
        ),
    ]
