# Generated by Django 3.2 on 2022-02-18 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0012_alter_company_vat_prefix'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dataprotection',
            name='cookies_international',
        ),
        migrations.AddField(
            model_name='dataprotection',
            name='privacy_policy',
            field=models.TextField(blank=True, max_length=3500, null=True),
        ),
        migrations.AddField(
            model_name='dataprotection',
            name='slug',
            field=models.SlugField(allow_unicode=True, editable=False, max_length=250, null=True),
        ),
    ]
