# Generated by Django 3.2 on 2022-02-20 11:30

import dashboard.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0018_auto_20220218_1313'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=50)),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
                ('subtitle', models.CharField(blank=True, max_length=100, null=True)),
                ('banner_image', models.ImageField(upload_to=dashboard.models.get_banner_image_upload_path, validators=[django.core.validators.FileExtensionValidator(['png', 'jpg', 'jpeg'])])),
                ('image_url', models.CharField(blank=True, default=None, max_length=250, null=True)),
                ('button_text', models.CharField(default='Ir', max_length=50)),
                ('text_color', models.CharField(default='#000000', max_length=7)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='HomeSlider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(max_length=50, unique=True)),
                ('slider_image', models.ImageField(upload_to=dashboard.models.get_banner_image_upload_path, validators=[django.core.validators.FileExtensionValidator(['png', 'jpg', 'jpeg'])])),
                ('image_url', models.CharField(blank=True, default=None, max_length=250, null=True)),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
                ('link_to', models.CharField(max_length=400)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
