# Generated by Django 3.2 on 2022-02-20 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0019_homebanner_homeslider'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homebanner',
            name='slug',
            field=models.SlugField(allow_unicode=True, editable=False, max_length=250),
        ),
        migrations.AlterField(
            model_name='homeslider',
            name='slug',
            field=models.SlugField(allow_unicode=True, editable=False, max_length=250),
        ),
    ]
