# Generated by Django 3.2 on 2022-02-20 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0020_auto_20220220_1232'),
    ]

    operations = [
        migrations.AddField(
            model_name='homebanner',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
