# Generated by Django 3.2 on 2022-02-21 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0021_homebanner_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='homebanner',
            name='link_to',
            field=models.CharField(max_length=400, null=True),
        ),
        migrations.AddField(
            model_name='homeslider',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
