# Generated by Django 3.2 on 2022-02-22 21:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0024_auto_20220222_2037'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homebanner',
            name='image_url',
        ),
        migrations.RemoveField(
            model_name='homeslider',
            name='image_url',
        ),
    ]
