# Generated by Django 3.2 on 2022-02-22 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0025_auto_20220222_2231'),
    ]

    operations = [
        migrations.AddField(
            model_name='homebanner',
            name='image_url',
            field=models.CharField(blank=True, default=None, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='homeslider',
            name='image_url',
            field=models.CharField(blank=True, default=None, max_length=250, null=True),
        ),
    ]
