# Generated by Django 3.2 on 2022-03-03 15:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0027_providers'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='providers',
            table='providers',
        ),
    ]
