# Generated by Django 3.2 on 2022-03-03 15:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0028_alter_providers_table'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Providers',
            new_name='Provider',
        ),
        migrations.AlterModelTable(
            name='provider',
            table='provider',
        ),
    ]
