# Generated by Django 3.2 on 2022-03-03 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0029_auto_20220303_1613'),
    ]

    operations = [
        migrations.AddField(
            model_name='provider',
            name='last_imported',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
