# Generated by Django 3.2 on 2022-03-03 16:40

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0030_provider_last_imported'),
    ]

    operations = [
        migrations.AddField(
            model_name='provider',
            name='type',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, default='', max_length=50), default=[], size=100),
        ),
    ]
